version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: latest
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore Api/Api.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build Api/Api.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release -r linux-x64 --self-contained false Api/Api.csproj
      
artifacts:
  files:
    - '**/*'
  base-directory: ./Api/bin/Release/netcoreapp5.0/linux-x64/publish/
  discard-paths: no
